### ISSUE TITLE
null pointer exception when parsing this xml model

### ISSUE THREAD

**Issue by pschaus** [xcsp3team/XCSP3-Java-Tools#14]
That I created using xcsp3 tools (all the files attached)
[xcsp3-bug.zip](https://github.com/xcsp3team/XCSP3-Java-Tools/files/1850618/xcsp3-bug.zip)
The stack-trace looks like:

java.lang.NullPointerException
	at org.xcsp.parser.loaders.CtrLoaderInteger.intension(CtrLoaderInteger.java:278)
	at org.xcsp.parser.loaders.CtrLoaderInteger.load(CtrLoaderInteger.java:164)
	at org.xcsp.parser.XCallbacks.loadCtr(XCallbacks.java:527)
	at org.xcsp.parser.XCallbacks.loadConstraints(XCallbacks.java:429)
	at org.xcsp.parser.XCallbacks.loadConstraints(XCallbacks.java:407)
	at org.xcsp.parser.XCallbacks.loadInstance(XCallbacks.java:297)
	at org.xcsp.parser.XCallbacks.loadInstance(XCallbacks.java:320)
	at xcsp3.XCSP3.<init>(XCSP3.java:69)
	at xcsp3.XCSP3.main(XCSP3.java:652)

**Comment by xcsp3team** [comment]
It seems that it is because of the commas in the id of variables.
It is forbidden to have this symbol. So if you change the name, it should be ok (I made a quick test).
Please, confirm me.

**Comment by pschaus** [comment]
Thanks! I confirm.  Suggestion: maybe an exception should be thrown or a silent replacement of "," by ";"

**Comment by xcsp3team** [comment]
I have added a control for the ids in the parser code.
