### ISSUE TITLE
Strange bug in org.xcsp.common.Utilities::join(Object,String) and its issue

### ISSUE THREAD

**Issue by jlejeunelip6** [xcsp3team/XCSP3-Java-Tools#20]
Hi,

I am working with the XCSP3-java-tool to parse XCSP files. When I try to parse iteratively (in the same JVM) all xml files given in the instancesTest directory I have a bug  with  the following files : Nonogram-001-regular.xml, Nonogram-001-table.xml, QuasiGroup-7-09.xml, RadarSurveillance-8-24-3-2-00.xml and qwh-o30-h374-01.xml  

The bug appears only (but not sometimes not) when we parse these files after the other ones.

The bug comes from the building of matrix variables (leading normally to the format x[i][j]) which sometimes produce x[ij] (Exception are listed at the end of the messages).

After several hours of searching (and no rational explanation), the source of the bug would be the line 519 of the file Utilities.java especially with the expresison `i < length - 1 ? delimiter : ""` in the second append call. 
May be because of an optimisation of javac or a jvm speculation execution, it seems that sometimes it is the else part which wins although the test is true.

By replacing this expression by `if (i < length - 1) sb.append(delimiter)`, the bug does not appear anymore.
 
I have no rational explanation for this bug. If you have it, thanks a lot for the feed back.

Regards

list of exceptions inducing by the bug :
 - qwh-o30-h374-01.xml `Fatal Error: Duplicate id x[110]
        java.lang.RuntimeException
	at org.xcsp.common.Utilities.control(Utilities.java:411)
	at org.xcsp.parser.callbacks.XCallbacks$Implem.manageIdFor(XCallbacks.java:202)
	at org.xcsp.parser.callbacks.XCallbacks.loadVar(XCallbacks.java:369)
	at org.xcsp.parser.callbacks.XCallbacks.lambda$loadArray$2(XCallbacks.java:411)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.xcsp.parser.callbacks.XCallbacks.loadArray(XCallbacks.java:411)
	at org.xcsp.parser.callbacks.XCallbacks.loadVariables(XCallbacks.java:345)
	at org.xcsp.parser.callbacks.XCallbacks.loadInstance(XCallbacks.java:302)
	at org.xcsp.parser.callbacks.XCallbacks.loadInstance(XCallbacks.java:328)
	at fr.semafor.cocos.xcsp.XCSP3ToComodel.<init>(XCSP3ToComodel.java:85)
	at fr.semafor.cocos.xcsp.test.SplitXCSP.main(SplitXCSP.java:23)`
 - RadarSurveillance-8-24-3-2-00.xml : `
       java.lang.NullPointerException: Cannot read the array length because "scope" is null
	at org.xcsp.parser.loaders.CtrLoaderInteger.intension(CtrLoaderInteger.java:316)
	at org.xcsp.parser.loaders.CtrLoaderInteger.load(CtrLoaderInteger.java:185)
	at org.xcsp.parser.callbacks.XCallbacks.loadCtr(XCallbacks.java:543)
	at org.xcsp.parser.callbacks.XCallbacks.loadConstraints(XCallbacks.java:444)
	at org.xcsp.parser.callbacks.XCallbacks.loadConstraints(XCallbacks.java:422)
	at org.xcsp.parser.callbacks.XCallbacks.loadInstance(XCallbacks.java:305)
	at org.xcsp.parser.callbacks.XCallbacks.loadInstance(XCallbacks.java:328)
	at fr.semafor.cocos.xcsp.XCSP3ToComodel.<init>(XCSP3ToComodel.java:85)
	at fr.semafor.cocos.xcsp.test.SplitXCSP.main(SplitXCSP.java:23)`
 - QuasiGroup-7-09.xml : `	 java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Long (java.lang.String and java.lang.Long are in module java.base of loader 'bootstrap')
       at org.xcsp.parser.loaders.CtrLoaderInteger.trInteger(CtrLoaderInteger.java:70)
	at org.xcsp.parser.loaders.CtrLoaderInteger.conditionEq(CtrLoaderInteger.java:611)
	at org.xcsp.parser.loaders.CtrLoaderInteger.element(CtrLoaderInteger.java:617)
	at org.xcsp.parser.loaders.CtrLoaderInteger.load(CtrLoaderInteger.java:236)
	at org.xcsp.parser.callbacks.XCallbacks.loadCtr(XCallbacks.java:543)
	at org.xcsp.parser.callbacks.XCallbacks.loadConstraints(XCallbacks.java:444)
	at org.xcsp.parser.callbacks.XCallbacks.loadConstraints(XCallbacks.java:422)
	at org.xcsp.parser.callbacks.XCallbacks.loadInstance(XCallbacks.java:305)
	at org.xcsp.parser.callbacks.XCallbacks.loadInstance(XCallbacks.java:328)
	at fr.semafor.cocos.xcsp.XCSP3ToComodel.<init>(XCSP3ToComodel.java:85)
	at fr.semafor.cocos.xcsp.test.SplitXCSP.main(SplitXCSP.java:23)
org.xcsp.parser.WrongTypeException: Wrong parameter type in constraint:
element()
	list() : [x[01], x[11], x[21], x[31], x[41], x[51], x[61], x[71], x[81]]
	index() : x[1][0]
	value() : y[0][1]
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Long (java.lang.String and java.lang.Long are in module java.base of loader 'bootstrap')
	at org.xcsp.parser.callbacks.XCallbacks.loadConstraints(XCallbacks.java:447)
	at org.xcsp.parser.callbacks.XCallbacks.loadConstraints(XCallbacks.java:422)
	at org.xcsp.parser.callbacks.XCallbacks.loadInstance(XCallbacks.java:305)
	at org.xcsp.parser.callbacks.XCallbacks.loadInstance(XCallbacks.java:328)
	at fr.semafor.cocos.xcsp.XCSP3ToComodel.<init>(XCSP3ToComodel.java:85)
	at fr.semafor.cocos.xcsp.test.SplitXCSP.main(SplitXCSP.java:23)`
- Nonogram-001-table.xml : `java.lang.RuntimeException
	at org.xcsp.common.Utilities.control(Utilities.java:411)
	at org.xcsp.parser.callbacks.XCallbacks$Implem.manageIdFor(XCallbacks.java:202)
	at org.xcsp.parser.callbacks.XCallbacks.loadVar(XCallbacks.java:369)
	at org.xcsp.parser.callbacks.XCallbacks.lambda$loadArray$2(XCallbacks.java:411)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.xcsp.parser.callbacks.XCallbacks.loadArray(XCallbacks.java:411)
	at org.xcsp.parser.callbacks.XCallbacks.loadVariables(XCallbacks.java:345)
	at org.xcsp.parser.callbacks.XCallbacks.loadInstance(XCallbacks.java:302)
	at org.xcsp.parser.callbacks.XCallbacks.loadInstance(XCallbacks.java:328)
	at fr.semafor.cocos.xcsp.XCSP3ToComodel.<init>(XCSP3ToComodel.java:85)
	at fr.semafor.cocos.xcsp.test.SplitXCSP.main(SplitXCSP.java:23)`
- Nonogram-001-regular.xml : `java.lang.RuntimeException
	at org.xcsp.common.Utilities.control(Utilities.java:411)
	at org.xcsp.parser.callbacks.XCallbacks$Implem.manageIdFor(XCallbacks.java:202)
	at org.xcsp.parser.callbacks.XCallbacks.loadVar(XCallbacks.java:369)
	at org.xcsp.parser.callbacks.XCallbacks.lambda$loadArray$2(XCallbacks.java:411)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.xcsp.parser.callbacks.XCallbacks.loadArray(XCallbacks.java:411)
	at org.xcsp.parser.callbacks.XCallbacks.loadVariables(XCallbacks.java:345)
	at org.xcsp.parser.callbacks.XCallbacks.loadInstance(XCallbacks.java:302)
	at org.xcsp.parser.callbacks.XCallbacks.loadInstance(XCallbacks.java:328)
	at fr.semafor.cocos.xcsp.XCSP3ToComodel.<init>(XCSP3ToComodel.java:85)
	at fr.semafor.cocos.xcsp.test.SplitXCSP.main(SplitXCSP.java:23)`

**Comment by xcsp3team** [comment]
Hi,

  I have modified the line (in two lines).
I have pushed the commit.
I can also post a new version on Maven (do you need that for testing ? if yes, I will post the version right now)

  Best,

 Christophe

**Comment by xcsp3team** [comment]
I have no explanation for this (but it seems to be a problem with the JVM).

**Comment by jlejeunelip6** [comment]
Hi, thanks a lot. I think that the problem come from  the JVM too. It would be nice if you can update the maven repository.
Best
Jonathan

**Comment by xcsp3team** [comment]
done.
